# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ocrworker.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0focrworker.proto\x12\tocrworker\"\x1e\n\x0bPingRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1f\n\x0cPingResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"d\n\x12\x45xtractTextRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x11\n\tfile_path\x18\x02 \x01(\t\x12\x10\n\x08language\x18\x03 \x01(\t\x12\x15\n\ruse_angle_cls\x18\x04 \x01(\x08\"R\n\x13\x45xtractTextResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t\x12\x12\n\nelapsed_ms\x18\x04 \x01(\x03\x32\x92\x01\n\tOcrWorker\x12\x37\n\x04Ping\x12\x16.ocrworker.PingRequest\x1a\x17.ocrworker.PingResponse\x12L\n\x0b\x45xtractText\x12\x1d.ocrworker.ExtractTextRequest\x1a\x1e.ocrworker.ExtractTextResponseB\x1e\n\x0f\x63om.example.ocrP\x01\xaa\x02\x08Ocr.Grpcb\x06proto3')

_PINGREQUEST = DESCRIPTOR.message_types_by_name['PingRequest']
_PINGRESPONSE = DESCRIPTOR.message_types_by_name['PingResponse']
_EXTRACTTEXTREQUEST = DESCRIPTOR.message_types_by_name['ExtractTextRequest']
_EXTRACTTEXTRESPONSE = DESCRIPTOR.message_types_by_name['ExtractTextResponse']
PingRequest = _reflection.GeneratedProtocolMessageType('PingRequest', (_message.Message,), {
  'DESCRIPTOR' : _PINGREQUEST,
  '__module__' : 'ocrworker_pb2'
  # @@protoc_insertion_point(class_scope:ocrworker.PingRequest)
  })
_sym_db.RegisterMessage(PingRequest)

PingResponse = _reflection.GeneratedProtocolMessageType('PingResponse', (_message.Message,), {
  'DESCRIPTOR' : _PINGRESPONSE,
  '__module__' : 'ocrworker_pb2'
  # @@protoc_insertion_point(class_scope:ocrworker.PingResponse)
  })
_sym_db.RegisterMessage(PingResponse)

ExtractTextRequest = _reflection.GeneratedProtocolMessageType('ExtractTextRequest', (_message.Message,), {
  'DESCRIPTOR' : _EXTRACTTEXTREQUEST,
  '__module__' : 'ocrworker_pb2'
  # @@protoc_insertion_point(class_scope:ocrworker.ExtractTextRequest)
  })
_sym_db.RegisterMessage(ExtractTextRequest)

ExtractTextResponse = _reflection.GeneratedProtocolMessageType('ExtractTextResponse', (_message.Message,), {
  'DESCRIPTOR' : _EXTRACTTEXTRESPONSE,
  '__module__' : 'ocrworker_pb2'
  # @@protoc_insertion_point(class_scope:ocrworker.ExtractTextResponse)
  })
_sym_db.RegisterMessage(ExtractTextResponse)

_PINGREQUEST._options = None
_PINGRESPONSE._options = None
_EXTRACTTEXTREQUEST._options = None
_EXTRACTTEXTRESPONSE._options = None
DESCRIPTOR._options = None
DESCRIPTOR._serialized_options = b'\n\017com.example.ocrP\001\252\002\010Ocr.Grpc'
# @@protoc_insertion_point(module_scope)
