# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ocrworker_pb2 as ocrworker__pb2


class OcrWorkerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/ocrworker.OcrWorker/Ping',
                request_serializer=ocrworker__pb2.PingRequest.SerializeToString,
                response_deserializer=ocrworker__pb2.PingResponse.FromString,
                )
        self.ExtractText = channel.unary_unary(
                '/ocrworker.OcrWorker/ExtractText',
                request_serializer=ocrworker__pb2.ExtractTextRequest.SerializeToString,
                response_deserializer=ocrworker__pb2.ExtractTextResponse.FromString,
                )


class OcrWorkerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExtractText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OcrWorkerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=ocrworker__pb2.PingRequest.FromString,
                    response_serializer=ocrworker__pb2.PingResponse.SerializeToString,
            ),
            'ExtractText': grpc.unary_unary_rpc_method_handler(
                    servicer.ExtractText,
                    request_deserializer=ocrworker__pb2.ExtractTextRequest.FromString,
                    response_serializer=ocrworker__pb2.ExtractTextResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ocrworker.OcrWorker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class OcrWorker(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ocrworker.OcrWorker/Ping',
            ocrworker__pb2.PingRequest.SerializeToString,
            ocrworker__pb2.PingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ExtractText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ocrworker.OcrWorker/ExtractText',
            ocrworker__pb2.ExtractTextRequest.SerializeToString,
            ocrworker__pb2.ExtractTextResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
